### ISSUE TITLE
Production sources depend on the specification

### ISSUE THREAD

**Issue by jcornaz** [brian-watkins/elm-spec#1]
Hi, 

Thanks a lot for providing this tool.

If I understand well when using `elm-spec` the `elm.json` is supposed to look like this:

```json
{
    "type": "application",
    "source-directories": [
        "src",
        "specs"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "brian-watkins/elm-spec": "2.2.0"
             // ...
        },
        "indirect": {
            // ...
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.2"
        },
        "indirect": {
            // ...
        }
    }
}
```

If this is correct, then it make the *production* code depend on `elm-spec` and our specifications. So one could (by mistake) call code in the specification sources or from `elm-spec` from the production sources.

That sounds very bad to me. Maybe I didn't understand the setup correctly?

Otherwise, could you change it so that we don't need to add dependency to our production code in order to write specifications?

**Comment by brian-watkins** [comment]
From your example `elm.json` it looks like you just have one `elm.json` for your project. You can set things up this way, but, for the reasons you point out, I like to create a separate `elm.json` just for the specs. Take a look at [this repo](https://github.com/brian-watkins/mindmaster) for an example -- you'll see a top level `elm.json` and then another `elm.json` in the `specs` folder.

One downside to this approach: If you have two `elm.json` files, this means you'll need to keep them in sync as you add dependencies; I realize that's not ideal but I don't know of a better solution right now.

It would be great if one could just add `elm-spec` to the `test-dependencies` in your `elm.json` but I'm not aware of a way to tell the elm compiler to make use of the dependencies listed in that section.

**Comment by jcornaz** [comment]
Ah... Ok. Of course, it makes a lot more sense like that.

Actually, reading again the documentation, I have to say it was clearly written. I just didn't understand.

My bad. Sorry, for the issue, and thanks again a lot for providing this tool!
